DEGRADED_TRAIN_DATA = './data/train/wm'
GT_TRAIN_DATA = './data/train/gt'
DEGRADED_VAL_DATA = './data/val/wm'
GT_VAL_DATA = './data/val/gt'
TRAIN_MODEL_PATH = './weights'
RESULT_PATH = './results'
TEST_PATH = './test'
